Added template details to library
uwmadison-chm/factuator pull request #7
Opened 2019-05-10 19:30 UTC by eguzman-wisc

Should do exactly as it's set out to, definitely increased processing time by a bit.

2019-05-10 19:49 UTC, dgfitch requested changes
OK, cool. But I want to make it a reused function instead of copy and pasting. Because I'm a stickler like that - and it will make it easier to change if we need to...

2019-05-19 20:02 UTC, eguzman-wisc commented
Made the changes you requested!

2019-05-20 14:26 UTC, dgfitch commented on selfreportlibrary.py
> +        #category.save(newpage, "Automated edit to build construct categories on self-report library")
You've got this commented out now, but the details function looks great!

2019-06-12 01:38 UTC, merged

2019-06-12 01:39 UTC, dgfitch commented
Let me know if you see issues with this merge, I'll check it out tomorrow.